[theme]
base = "light"
primaryColor = "#BB3344"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F5F5"
textColor = "#292426"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
